# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 10:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_email', models.EmailField(blank=True, max_length=254)),
                ('c_ppt', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Job_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_position', models.CharField(blank=True, max_length=30, null=True)),
                ('list_of_student', models.CharField(blank=True, max_length=500, null=True)),
                ('c_description', models.CharField(max_length=500, null=True)),
                ('date_published', models.DateField(null=True)),
                ('date_expiry', models.DateField(null=True)),
                ('c_ctc_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('c_branch', models.CharField(choices=[('CS', 'computer_science'), ('ME', 'mechanical'), ('EE', 'electrical')], default='CS', max_length=10)),
                ('c_course', models.CharField(choices=[('BTECH', 'bachelors'), ('MTECH', 'masters'), ('PHD', 'philospher')], default='BTECH', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('c_company_name', models.CharField(blank=True, max_length=20, null=True)),
                ('c_details', models.TextField(blank=True)),
                ('c_verified', models.BooleanField(default=False)),
                ('c_verification', models.IntegerField(blank=True, default=0)),
                ('c_contact', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('c_email', models.EmailField(blank=True, max_length=254)),
                ('c_password', models.CharField(blank=True, max_length=30)),
                ('c_confirm_password', models.CharField(blank=True, max_length=30)),
                ('c_ppt', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
        migrations.AddField(
            model_name='job_desc',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Register'),
        ),
        migrations.AddField(
            model_name='edit_details',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Register'),
        ),
    ]
