# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 15:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170312_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='c_contact',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='register',
            name='c_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
