# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_edit_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='c_verification',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='c_verified',
            field=models.BooleanField(default=False),
        ),
    ]
