# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170319_2236'),
        ('company', '0007_auto_20170324_1948'),
    ]

    operations = [
    ]
