# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_merge_20170324_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='c_ad_details',
        ),
    ]
