# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_register_c_ad_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_ctc_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('c_branch', models.CharField(choices=[('BTECH', 'bachelors'), ('MTECH', 'masters'), ('PHD', 'philospher')], default='CS', max_length=10)),
                ('c_requirements', models.CharField(choices=[('CS', 'computer_science'), ('ME', 'mechanical'), ('EE', 'electrical')], default='BTECH', max_length=5)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Register')),
            ],
        ),
    ]
