# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20170406_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_desc',
            name='c_position',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
