# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_job_desc_c_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_desc',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Register'),
        ),
    ]
