# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20170406_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='c_company_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
