# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_register_c_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit_details',
            old_name='c_selected_students',
            new_name='c_ppt',
        ),
        migrations.RemoveField(
            model_name='edit_details',
            name='c_branches_allowed',
        ),
        migrations.RemoveField(
            model_name='edit_details',
            name='c_ctc_offered',
        ),
        migrations.RemoveField(
            model_name='edit_details',
            name='c_name',
        ),
        migrations.RemoveField(
            model_name='edit_details',
            name='c_requirements',
        ),
    ]
