# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20170406_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='c_ppt',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
