# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_register_c_ppt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='c_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
