# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20170408_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_desc',
            name='c_ctc_offered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='job_desc',
            name='c_position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
