# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20170408_2247'),
        ('company', '0020_auto_20170408_2034'),
    ]

    operations = [
    ]
