# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_merge_20170408_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_desc',
            name='c_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
