# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=250, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_username', models.CharField(default='', max_length=250)),
                ('s_name', models.CharField(blank=True, max_length=250)),
                ('s_password', models.CharField(blank=True, max_length=250)),
                ('s_confirm_password', models.CharField(blank=True, max_length=250)),
                ('dob', models.DateField()),
                ('emailid', models.EmailField(blank=True, max_length=254)),
                ('branch', models.CharField(choices=[('BTECH', 'bachelors'), ('MTECH', 'masters'), ('PHD', 'philospher')], default='CS', max_length=10)),
                ('course', models.CharField(choices=[('CS', 'computer_science'), ('ME', 'mechanical'), ('EE', 'electrical')], default='BTECH', max_length=5)),
                ('s_verified', models.BooleanField(default=False)),
                ('s_verification', models.IntegerField(blank=True, default=0)),
                ('contactno', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
