# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField()),
                ('got_offer', models.CharField(max_length=250, null=True)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Job_desc')),
            ],
        ),
        migrations.CreateModel(
            name='Edit_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=250, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=254)),
                ('qualification', models.CharField(blank=True, max_length=250, null=True)),
                ('resume', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_text', models.CharField(max_length=250, null=True)),
                ('old', models.BooleanField(default=True)),
                ('jobid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Job_desc')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_username', models.CharField(default='', max_length=250)),
                ('s_name', models.CharField(blank=True, max_length=250)),
                ('s_password', models.CharField(blank=True, max_length=250)),
                ('s_confirm_password', models.CharField(blank=True, max_length=250)),
                ('dob', models.DateField()),
                ('emailid', models.EmailField(blank=True, max_length=254)),
                ('branch', models.CharField(choices=[('CS', 'computer_science'), ('ME', 'mechanical'), ('EE', 'electrical')], default='CS', max_length=10)),
                ('course', models.CharField(choices=[('BTECH', 'bachelors'), ('MTECH', 'masters'), ('PHD', 'philospher')], default='BTECH', max_length=5)),
                ('s_verified', models.BooleanField(default=False)),
                ('s_verification', models.IntegerField(blank=True, default=0)),
                ('contactno', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='notifications',
            name='stdid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentDB'),
        ),
    ]
