# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=250)),
                ('dob', models.DateField(max_length=12)),
                ('emailid', models.CharField(max_length=250)),
                ('contactno', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('profile_pic', models.CharField(max_length=500)),
            ],
        ),
    ]
