# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='profile_pic',
            field=models.FileField(upload_to=b''),
        ),
    ]
