# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20170406_1437'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Job_desc')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_text', models.CharField(max_length=250)),
                ('new', models.BooleanField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Job_desc')),
            ],
        ),
        migrations.AddField(
            model_name='edit_details',
            name='qualification',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='edit_details',
            name='resume',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
