# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='stdid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentDB'),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='jobid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Job_desc'),
        ),
    ]
