# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170408_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='job_id',
            new_name='jobid',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='job_id',
            new_name='jobid',
        ),
    ]
