# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=250, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='studentdb',
            name='branch',
            field=models.CharField(choices=[('BTECH', 'bachelors'), ('MTECH', 'masters'), ('PHD', 'philospher')], default='CS', max_length=10),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='course',
            field=models.CharField(choices=[('CS', 'computer_science'), ('ME', 'mechanical'), ('EE', 'electrical')], default='BTECH', max_length=5),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='s_confirm_password',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='s_password',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='s_username',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='s_verification',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='s_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='contactno',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='emailid',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='s_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='edit_details',
            name='s_perm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentDB'),
        ),
    ]
