# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170408_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='new',
            new_name='old',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='got_offer',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
