# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20170408_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='stdid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentDB'),
        ),
    ]
