# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_notifications_stdid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='jobid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Job_desc'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='n_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='old',
            field=models.BooleanField(default=True),
        ),
    ]
